locations:
  0: DEU_Neuweiler-1
  1: kackertstrasse
  2: thiergarten_01

class_to_obstacleType:
  car: car
  truck: truck
  bus: bus
  pedestrian: pedestrian
  bicycle: bicycle
  motorcycle: motorcycle
  trailer: truck
  van: truck
