image: python:3.8

stages:
- style
- test
- build

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install
  - source .venv/bin/activate

convert_highd:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - poetry run python -m unittest tests/test_highD.py

convert_ind:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - poetry run python -m unittest tests/test_inD.py

convert_round:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - poetry run python -m unittest tests/test_rounD.py

convert_exid:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - poetry run python -m unittest tests/test_exiD.py

convert_interaction:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - poetry run python -m unittest tests/test_INTERACTION.py
  timeout: 3h

test_mona :
  stage : test
  image : python:3.8
  script :
    - poetry run python -m unittest tests/test_mona.py

test_sind :
  stage : test
  image : python:3.8
  script :
    - poetry run python -m unittest tests/test_sind.py

flake8 :
  stage : style
  before_script : [ ]
  script :
    - pip install flake8 flake8-todo
    - flake8 commonroad_dataset_converter
  allow_failure : true

publish_internal:
  stage: build
  when: manual
  only:
    - master
  script:
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  environment:
    name: staging
    url: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi

publish_pypi:
  stage: build
  when: manual
  only:
    - master
  script:
    - poetry build
    - poetry publish -u ${CR_PYPI_RELEASE_USERNAME} -p ${CR_PYPI_RELEASE_PASSWORD}
  environment:
    name: production
    url: https://pypi.org/project/commonroad-dataset-converter