image: continuumio/anaconda3

stages:
- prepare
- test
- build

before_script:
  - apt-get update -y > /dev/null
  - apt-get install -y --no-install-recommends apt-utils dialog build-essential > /dev/null
  - conda create -n cr37 python=3.7
  - source activate cr37
  - pip install -r requirements.txt
  - make install
  - make build

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.

convert_highd:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - python -m unittest commonroad_dataset_converter/tests/test_highD.py
  cache:
    key: download-cache

convert_ind:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - python -m unittest commonroad_dataset_converter/tests/test_inD.py
  cache:
    key: download-cache
  
convert_round:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - python -m unittest commonroad_dataset_converter/tests/test_rounD.py
  cache:
    key: download-cache

convert_interaction:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - python -m unittest commonroad_dataset_converter/tests/test_INTERACTION.py
  cache:
    key: download-cache
  timeout: 3h
