image: python:3.8

stages:
- test
- build

cache:
  paths:
    - .venv

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install
  - source .venv/bin/activate

convert_highd:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - poetry run python -m unittest tests/test_highD.py
  cache:
    key: download-cache

convert_ind:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - poetry run python -m unittest tests/test_inD.py
  cache:
    key: download-cache

convert_interaction:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH'
      allow_failure: true
      when: manual
  script:
    - poetry run python -m unittest tests/test_INTERACTION.py
  cache:
    key: download-cache
  timeout: 3h

publish_internal:
  stage: build
  when: manual
  only:
    - master
  script:
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}

publish_pypi:
  stage: build
  when: manual
  only:
    - master
  script:
    - poetry build
    - poetry publish -u ${CR_PYPI_RELEASE_USERNAME} -p ${CR_PYPI_RELEASE_PASSWORD}