author: Niels Mündler, Xiao Wang
affiliation: Technical University of Munich, Germany
source: The Intersection Drone Dataset (inD)
tags: [intersection, multi_lane, urban, oncoming_traffic, speed_limit]

locations:
    1: Bendplatz
    2: frankenberg
    3: heckstrasse
    4: aseag

location_benchmark_id:
    1: AAH-1
    2: AAH-2
    3: AAH-3
    4: AAH-4

class_to_obstacleType:
    car: car
    truck_bus: bus
    pedestrian: pedestrian
    bicycle: pedestrian


