author: TUM
affiliation: CPS
source: MONA Dataset
origin: [692000.0, 5340000.0]
dataset_url: mona.cps.cit.tum.de/mona/processed
map_url: https://mona.cps.cit.tum.de/mona/assets/maps/
maps :
  east : DEU_MONAEast-2.xml
  west : DEU_MONAWest-2.xml
  merge : DEU_MONAMerge-2.xml
